[theme]
primaryColor = "#4ADE80"
backgroundColor = "#0A0F16"
secondaryBackgroundColor = "#0D1117"
textColor = "#CBD5E1"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
